[manifest]
version = "1.0.0"
priority = 10

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "      UIBox_button({button = 'usage', label = {localize('k_card_stats')}, minw = 7.5, minh =1, focus_args = {nav = 'wide'}}),"
position = "at"
payload = ""
match_indent = true